Develop matrix build (#3)
* added matrix os

* Try setup.py install

* FIX encoding issue on windows

running setup.py on windows throws the following error.

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5551: character maps to <undefined>

* FIX path issues on windows

Must reference os.sep instead of /

* Fix remaining winows path issues

* Add older os versions

Co-authored-by: WaylonWalker <walker_waylon_s@cat.com>